group = "marais"
artifact = "testprojectkt"
version = "0.1.0"

[dependencies]
# Compile and runtime dependencies
compileRuntime = [
    "org.apache.logging.log4j:log4j-api:2.14.1"
]
# Runtime only dependencies
runtime = [
    { group = "org.apache.logging.log4j", artifact = "log4j-core", version = "2.14.1" }
]
# Compile only
compile = []
transitive = []

[[entrypoints]]
class = "MainKt"
