group = "marais"
artifact = "testproject"
version = "0.1.0"
base_package = ""
dependencies = [
    "org.apache.logging.log4j:log4j-api:2.14.1",
    { group = "org.apache.logging.log4j", artifact = "log4j-core", version = "2.14.1" },
]

[[entrypoints]]
class = "Main"

[[entrypoints]]
name = "Other"
class = "OtherMain"
