name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-linux:
    name: Build binaries (linux) and publish on crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
          components: rust-docs
      - name: Build release
        run: cargo build --release
      - name: Upload release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/jcargo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish release on crates.io
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
  release-windows:
    name: Build binaries (windows)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
          components: rust-docs
      - name: Build release
        run: cargo build --release
      - name: Upload release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/jcargo.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
